### ISSUE TITLE
Not able to make it working with EATON USB

### ISSUE THREAD

**Issue by aryedevops** [upshift-docker/nut-upsd#1]
Hi, I have already configured my docker to work with EATON following your descriptions.
I have tried so many times with NO luck at all.

I am getting Errors:
`+ chgrp -R nut /etc/nut /dev/bus/usb
+ chmod -R o-rwx /etc/nut
+ /usr/sbin/upsdrvctl start
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
Using subdriver: MGE HID 1.39
USB communication driver 0.33
+ /usr/sbin/upsd
fopen /var/run/nut/upsd.pid: No such file or directory
listening on 0.0.0.0 port 3493
Network UPS Tools upsd 2.7.4
Connected to UPS [EATON]: usbhid-ups-EATON
+ exec /usr/sbin/upsmon -D
Network UPS Tools upsmon 2.7.4
   0.000000	fopen /var/run/upsmon.pid: No such file or directory
   0.000037	UPS: EATON@localhost (master) (power value 1)
   0.000059	debug level is '1'
   0.000469	Trying to connect to UPS [EATON@localhost]
   0.001109	Logged into UPS EATON@localhost`
I am NOT able to run the Tools at all - Please let me know what to do in order to make it working?

This is my docker-compose file:
```
version: "3.7"
services:
  nut-UPS:
    image: upshift/nut-upsd:latest
    container_name: Nut-UPS
    restart: always
    environment:
      - TZ=Asia/Jerusalem
      - UPS_NAME=EATON
      - UPS_DRIVER=usbhid-ups
      - UPS_PORT=auto
      - API_USER=${NUTUPS_USERNAME}
      - API_PASSWORD=${NUTUPS_PASSWORD}
      - ADMIN_PASSWORD=${NUTADMIN_PASSWORD}
    devices:
      - /dev/bus/usb/002/004:/dev/bus/usb/002/004
    volumes:
      - ./config/:/etc/nut/
    privileged: true
    network_mode: bridge
    ports:
      - 3493:3493
```
I do have `.env` file for storing the above variable in the same folder.
Please do let me understand why I am Not able to make it run?
also getting `fopen /var/run/nut/upsd.pid: No such file or directory` and `0.000000	fopen /var/run/upsmon.pid: No such file or directory`

Thanks

**Comment by williamdes** [comment]
You can use my image and this config
```yml
    nut-ups:
        image: botsudo/nut-upsd
        dns_search: project.local
        hostname: nut-upsd.project.local
        container_name: nut-upsd
        networks:
            dc2_network_infra:
                aliases:
                    - my-upsd.project.local
        devices:
            # UPS (can be more precise but the system often changes numbers)
            - /dev/bus/usb/001:/dev/bus/usb/001
        device_cgroup_rules:
            # https://dev.to/jeetparekh/accessing-devices-from-inside-a-docker-container-without-using-the-privileged-flag-1dd8
            # ls -l /dev/bus/usb/001/095
            - 'a 189:* rwm'
        mem_limit: 200m
        mem_reservation: 50m
        restart: on-failure:2
```

```sh
bash-5.1# upsc ups@my-upsd.project.local
```
